#!/bin/bash

pushd `dirname ${BASH_SOURCE[0]}` > /dev/null
GIT_ROOT=`pwd -P`
popd > /dev/null

if [ -e "$GIT_ROOT/.vimrc" ]; then
   ln -s $GIT_ROOT/.vimrc $HOME/.vimrc
else
   echo "$GIT_ROOT/.vimrc does not exist. Bailing out!"
fi
